[pytest]
testpaths = tests
norecursedirs =
    .git
    .venv
    .mypy_cache
    .pytest_cache
    .cache
    logs
    github-repos
    tools
    experimental
    backups
    data
    reports
addopts = -ra
filterwarnings =
    ignore:.*websockets\.legacy is deprecated.*:DeprecationWarning
    ignore:Field name "stop_price" in "Order" shadows an attribute in parent "ModelWithID":UserWarning
    ignore:Field name "stop_price" in "StopLossRequest" shadows an attribute in parent "NonEmptyRequest":UserWarning
    ignore:Field name "stop_price" in "ReplaceOrderRequest" shadows an attribute in parent "NonEmptyRequest":UserWarning
    ignore:Field name "stop_price" in "StopOrderRequest" shadows an attribute in parent "OrderRequest":UserWarning
    ignore:Field name "stop_price" in "StopLimitOrderRequest" shadows an attribute in parent "OrderRequest":UserWarning
    ignore:The NumPy module was reloaded \(imported a second time\)\. This can in some cases result in small but subtle issues and is discouraged\.:UserWarning
