"""
Data Sync Utility - Ensures all data sources are synchronized.

Verifies that:
1. DuckDB matches the latest date in daily_features.parquet
2. All local data files are current (updated today)
3. Rebuilds DuckDB views if out of sync

Run modes:
- check: Just verify sync status
- sync: Verify and fix any issues
- rebuild: Force rebuild all DuckDB views

Usage:
    from autotrade.utils.data_sync import DataSyncManager
    sync = DataSyncManager()
    status = sync.check_sync_status()
    if not status['all_synced']:
        sync.sync_all()
"""

from __future__ import annotations

import copy
import logging
from pathlib import Path
from datetime import datetime, date, time, timedelta
from typing import Dict, Optional, Any, Tuple
from dataclasses import dataclass

import pandas as pd

# Circular import safe imports
from autotrade.data_ingestion.paths import get_ingestion_paths
from autotrade.utils.security_metadata import get_nasdaq_screener_path
from autotrade.utils.market_time import (
    MARKET_CLOSE_LOCAL,
    get_market_now,
    is_trading_day,
    last_trading_day,
    expected_core_market_data_date,
)

logger = logging.getLogger("AutoTrade.DataSync")

# ============================================================================
# Path Configuration
# ============================================================================

INGESTION_PATHS = get_ingestion_paths()
DOWNDAY_ROOT = INGESTION_PATHS.downday_root

# Source data files (generated daily by DownDay pipeline)
DATA_SOURCES = {
    "daily_features_parquet": INGESTION_PATHS.daily_features_parquet,
    "hourly_prices_parquet": INGESTION_PATHS.hourly_prices_parquet,
    "daily_features_h5": INGESTION_PATHS.daily_features_h5,
    "prices_daily_csv": INGESTION_PATHS.prices_daily_csv,
    "prices_hourly_csv": INGESTION_PATHS.prices_hourly_csv,
    "market_data_duckdb": INGESTION_PATHS.market_data_duckdb,
}

# AutoTrade local cache
AUTOTRADE_DATA_DIR = Path(__file__).parent.parent.parent / "data"
TRADING_CACHE_DB = AUTOTRADE_DATA_DIR / "trading_cache.duckdb"


@dataclass
class SyncStatus:
    """Status of a data source synchronization."""

    source: str
    path: str
    exists: bool
    latest_date: Optional[str]
    file_modified: Optional[str]
    is_current: bool
    ticker_count: Optional[int] = None
    row_count: Optional[int] = None
    error: Optional[str] = None


@dataclass
class CoreDataFreshnessResult:
    """Canonical readiness verdict for core market data."""

    is_fresh: bool
    primary_date: Optional[str]
    expected_date: Optional[str]
    primary_tickers: int
    all_synced: bool
    age_days: Optional[int]
    checked_at: str
    blocking_reasons: list[str]

    def to_dict(self) -> Dict[str, Any]:
        return {
            "is_fresh": bool(self.is_fresh),
            "primary_date": self.primary_date,
            "expected_date": self.expected_date,
            "primary_tickers": int(self.primary_tickers or 0),
            "all_synced": bool(self.all_synced),
            "age_days": self.age_days,
            "checked_at": self.checked_at,
            "blocking_reasons": list(self.blocking_reasons),
            "pm_ready_for_execution": bool(self.is_fresh),
            "core_data_fresh": bool(self.is_fresh),
            "core_data_asof": self.primary_date,
        }


class DataSyncManager:
    """
    Manages synchronization between data sources.

    Primary source: daily_features.parquet (generated by DownDay pipeline)
    Ensures all other sources (DuckDB, CSVs) are in sync.
    """

    def __init__(self):
        """Initialize the sync manager."""
        self._status_cache: Dict[str, SyncStatus] = {}
        self._primary_date: Optional[str] = None
        self._duckdb_available = False
        self._sync_status_summary_cache: Optional[Dict[str, Any]] = None
        self._sync_status_summary_fingerprint: Optional[Tuple[Any, ...]] = None
        self._sync_status_summary_checked_at: Optional[datetime] = None
        # day-manager 2026-05-20: bumped 60s -> 600s (10min). With a 60s TTL,
        # any concurrent disk pressure (e.g. MomentumScannerDaemon reading
        # bars) caused _get_csv_info's full pd.read_csv + pd.to_datetime to
        # take longer than the TTL, creating an unresolvable re-read cascade
        # that hung run_day_manager_cycle. Fingerprint (mtime+size) still
        # invalidates the cache when files actually change, so freshness
        # is preserved.
        self._sync_status_summary_ttl_seconds = 600

        # Check DuckDB availability
        try:
            import duckdb

            self._duckdb = duckdb
            self._duckdb_available = True
        except ImportError:
            logger.warning("DuckDB not available - limited sync functionality")

    def _build_source_fingerprint(self) -> Tuple[Any, ...]:
        """
        Cheap fingerprint for cache invalidation.

        Uses stat metadata only so repeated freshness calls avoid re-reading
        parquet/CSV/H5/DuckDB content when the backing files have not changed.
        """
        fingerprint = []
        for source_name, path in DATA_SOURCES.items():
            try:
                stat = path.stat()
                fingerprint.append(
                    (
                        source_name,
                        True,
                        int(stat.st_mtime_ns),
                        int(stat.st_size),
                    )
                )
            except FileNotFoundError:
                fingerprint.append((source_name, False, 0, 0))
            except Exception:
                fingerprint.append((source_name, None, 0, 0))
        return tuple(fingerprint)

    def get_primary_latest_date(self) -> Tuple[Optional[str], int]:
        """
        Get the latest date from the primary data source (daily_features.parquet).

        Returns:
            Tuple of (latest_date_str, ticker_count)
        """
        parquet_path = DATA_SOURCES["daily_features_parquet"]

        if not parquet_path.exists():
            logger.error(f"Primary data source not found: {parquet_path}")
            return None, 0

        try:
            df = pd.read_parquet(parquet_path, columns=["ticker", "Date"])
            latest_date = df["Date"].max()
            ticker_count = df["ticker"].nunique()

            # Handle different date formats
            if hasattr(latest_date, "strftime"):
                latest_str = latest_date.strftime("%Y-%m-%d")
            else:
                latest_str = str(latest_date)[:10]

            self._primary_date = latest_str
            return latest_str, ticker_count

        except Exception as e:
            logger.error(f"Failed to read primary data source: {e}")
            return None, 0

    def check_source_status(self, source_name: str) -> SyncStatus:
        """
        Check sync status for a specific data source.

        Args:
            source_name: Key from DATA_SOURCES

        Returns:
            SyncStatus object
        """
        path = DATA_SOURCES.get(source_name)
        if not path:
            return SyncStatus(
                source=source_name,
                path="",
                exists=False,
                latest_date=None,
                file_modified=None,
                is_current=False,
                error="Unknown source",
            )

        if not path.exists():
            return SyncStatus(
                source=source_name,
                path=str(path),
                exists=False,
                latest_date=None,
                file_modified=None,
                is_current=False,
                error="File not found",
            )

        try:
            # Get file modification time
            mtime = datetime.fromtimestamp(path.stat().st_mtime)
            mtime_str = mtime.strftime("%Y-%m-%d %H:%M")

            # Get latest date from data based on file type
            latest_date = None
            ticker_count = None
            row_count = None

            if source_name.endswith("_parquet"):
                latest_date, ticker_count, row_count = self._get_parquet_info(path)
            elif source_name.endswith("_csv"):
                latest_date, ticker_count, row_count = self._get_csv_info(path)
            elif source_name.endswith("_duckdb"):
                latest_date, ticker_count, row_count = self._get_duckdb_info(path)
            elif source_name.endswith("_h5"):
                latest_date, ticker_count, row_count = self._get_h5_info(path)

            # Check if current (matches primary or within 1 day)
            is_current = False
            if latest_date and self._primary_date:
                try:
                    # Use pandas for robust parsing, normalize to naive
                    primary_dt = pd.to_datetime(self._primary_date).replace(tzinfo=None)
                    latest_dt = pd.to_datetime(latest_date[:10]).replace(tzinfo=None)
                    is_current = abs((primary_dt - latest_dt).days) <= 1
                except (ValueError, TypeError):
                    is_current = latest_date[:10] == self._primary_date[:10]

            return SyncStatus(
                source=source_name,
                path=str(path),
                exists=True,
                latest_date=latest_date,
                file_modified=mtime_str,
                is_current=is_current,
                ticker_count=ticker_count,
                row_count=row_count,
            )

        except Exception as e:
            return SyncStatus(
                source=source_name,
                path=str(path),
                exists=True,
                latest_date=None,
                file_modified=None,
                is_current=False,
                error=str(e),
            )

    def _get_parquet_info(self, path: Path) -> Tuple[Optional[str], int, int]:
        """Get latest date, ticker count, and row count from parquet file."""
        try:
            # First check available columns
            import pyarrow.parquet as pq

            schema = pq.read_schema(path)
            columns = schema.names

            # Find date column (could be 'Date', 'Datetime', 'date', etc.)
            date_col = None
            for col in columns:
                if col.lower() in ["date", "datetime"]:
                    date_col = col
                    break

            if not date_col:
                logger.debug(f"No date column found in {path}. Columns: {columns}")
                return None, 0, 0

            # Read only needed columns
            read_cols = ["ticker", date_col] if "ticker" in columns else [date_col]
            df = pd.read_parquet(path, columns=read_cols)

            latest = df[date_col].max()
            if hasattr(latest, "strftime"):
                latest_str = latest.strftime("%Y-%m-%d")
            else:
                latest_str = str(latest)[:10]

            ticker_count = df["ticker"].nunique() if "ticker" in df.columns else 0
            return latest_str, ticker_count, len(df)

        except Exception as e:
            logger.debug(f"Parquet info error for {path}: {e}")
            return None, 0, 0

    def _get_csv_info(self, path: Path) -> Tuple[Optional[str], int, int]:
        """Get latest date, ticker count, and row count from CSV file."""
        try:
            # Read just first few and last few rows for efficiency
            df = pd.read_csv(path, nrows=1000)
            date_col = next((c for c in df.columns if "date" in c.lower()), None)
            ticker_col = next(
                (c for c in df.columns if c.lower() in ["ticker", "symbol"]), None
            )

            if date_col:
                # Get full date range
                df_full = pd.read_csv(
                    path, usecols=[date_col, ticker_col] if ticker_col else [date_col]
                )
                latest = pd.to_datetime(df_full[date_col]).max()
                latest_str = latest.strftime("%Y-%m-%d")
                ticker_count = df_full[ticker_col].nunique() if ticker_col else 0
                return latest_str, ticker_count, len(df_full)
            return None, 0, 0
        except Exception as e:
            logger.debug(f"CSV info error: {e}")
            return None, 0, 0

    def _get_duckdb_info(self, path: Path) -> Tuple[Optional[str], int, int]:
        """Get latest date, ticker count, and row count from DuckDB."""
        if not self._duckdb_available:
            return None, 0, 0

        try:
            conn = self._duckdb.connect(str(path), read_only=True)

            # Check for daily_prices table
            tables = conn.execute("SHOW TABLES").fetchall()
            table_names = [t[0] for t in tables]

            if "daily_prices" in table_names:
                result = conn.execute("""
                    SELECT MAX(date), COUNT(DISTINCT symbol), COUNT(*)
                    FROM daily_prices
                """).fetchone()
                conn.close()

                if result and result[0]:
                    latest_str = str(result[0])[:10]
                    return latest_str, result[1], result[2]

            conn.close()
            return None, 0, 0

        except Exception as e:
            logger.debug(f"DuckDB info error: {e}")
            return None, 0, 0

    def _get_h5_info(self, path: Path) -> Tuple[Optional[str], int, int]:
        """Get latest date, ticker count, and row count from HDF5 file."""
        try:
            with pd.HDFStore(path, mode="r") as store:
                keys = store.keys()
                if not keys:
                    return None, 0, 0

                # Try to read the first key
                key = keys[0]
                df = store[key]

                if "Date" in df.columns:
                    latest = df["Date"].max()
                    if hasattr(latest, "strftime"):
                        latest_str = latest.strftime("%Y-%m-%d")
                    else:
                        latest_str = str(latest)[:10]

                    ticker_count = (
                        df["ticker"].nunique() if "ticker" in df.columns else 0
                    )
                    return latest_str, ticker_count, len(df)

            return None, 0, 0
        except Exception as e:
            logger.debug(f"H5 info error: {e}")
            return None, 0, 0

    def check_sync_status(self, force_refresh: bool = False) -> Dict[str, Any]:
        """
        Check synchronization status for all data sources.

        Returns:
            Dict with overall status and per-source details
        """
        fingerprint = self._build_source_fingerprint()
        now = datetime.now()
        if (
            not force_refresh
            and self._sync_status_summary_cache is not None
            and self._sync_status_summary_fingerprint == fingerprint
            and self._sync_status_summary_checked_at is not None
            and (now - self._sync_status_summary_checked_at).total_seconds()
            < self._sync_status_summary_ttl_seconds
        ):
            logger.debug("[DataSync] Reusing cached sync status summary")
            return copy.deepcopy(self._sync_status_summary_cache)

        # Get primary date first
        primary_date, primary_tickers = self.get_primary_latest_date()

        if not primary_date:
            result = {
                "all_synced": False,
                "primary_date": None,
                "primary_tickers": 0,
                "error": "Primary data source unavailable",
                "sources": {},
            }
            self._sync_status_summary_cache = copy.deepcopy(result)
            self._sync_status_summary_fingerprint = fingerprint
            self._sync_status_summary_checked_at = now
            return result

        logger.info(f"Primary data: {primary_date} ({primary_tickers} tickers)")

        # Check all sources
        sources = {}
        all_synced = True

        for source_name in DATA_SOURCES.keys():
            status = self.check_source_status(source_name)
            sources[source_name] = {
                "exists": status.exists,
                "latest_date": status.latest_date,
                "is_current": status.is_current,
                "ticker_count": status.ticker_count,
                "row_count": status.row_count,
                "file_modified": status.file_modified,
                "error": status.error,
            }

            if status.exists and not status.is_current:
                all_synced = False
                logger.warning(
                    f"  {source_name}: OUT OF SYNC "
                    f"(has {status.latest_date}, needs {primary_date})"
                )
            elif status.exists:
                logger.info(f"  {source_name}: OK ({status.latest_date})")

        result = {
            "all_synced": all_synced,
            "primary_date": primary_date,
            "primary_tickers": primary_tickers,
            "sources": sources,
            "checked_at": datetime.now().isoformat(),
        }
        self._sync_status_summary_cache = copy.deepcopy(result)
        self._sync_status_summary_fingerprint = fingerprint
        self._sync_status_summary_checked_at = now
        return result

    def sync_duckdb(self, force: bool = False) -> bool:
        """
        Sync DuckDB with latest parquet data.

        Creates/updates views in DuckDB that point to parquet files.

        Args:
            force: Force recreation even if already synced

        Returns:
            True if successful
        """
        if not self._duckdb_available:
            logger.error("DuckDB not available")
            return False

        duckdb_path = DATA_SOURCES["market_data_duckdb"]
        parquet_path = DATA_SOURCES["daily_features_parquet"]
        hourly_path = DATA_SOURCES["hourly_prices_parquet"]
        metadata_path = get_nasdaq_screener_path()

        if not parquet_path.exists():
            logger.error(f"Parquet source not found: {parquet_path}")
            return False

        try:
            import pyarrow.parquet as pq

            schema = pq.read_schema(parquet_path)
            parquet_cols = set(schema.names)
        except Exception as e:
            logger.warning(f"Could not read parquet schema: {e}")
            parquet_cols = set()

        try:
            conn = self._duckdb.connect(str(duckdb_path))

            # Create or replace views pointing to parquet files
            logger.info("Syncing DuckDB views to parquet files...")

            if metadata_path.exists():
                metadata_join = f"""
                    LEFT JOIN (
                        SELECT
                            UPPER(Symbol) AS meta_symbol,
                            NULLIF(TRIM(Sector), '') AS sector,
                            TRY_CAST(REPLACE(CAST("Market Cap" AS VARCHAR), ',', '') AS DOUBLE) AS market_cap
                        FROM read_csv_auto('{metadata_path.as_posix()}', HEADER=TRUE)
                    ) meta
                        ON UPPER(p.ticker) = meta.meta_symbol
                """
            else:
                metadata_join = ""

            if "market_cap" in parquet_cols and metadata_join:
                mkt_cap_select = (
                    ", COALESCE(p.market_cap, meta.market_cap) AS market_cap"
                )
            elif "market_cap" in parquet_cols:
                mkt_cap_select = ", p.market_cap AS market_cap"
            elif metadata_join:
                mkt_cap_select = ", meta.market_cap AS market_cap"
            else:
                mkt_cap_select = ", NULL as market_cap"

            if "sector" in parquet_cols and metadata_join:
                sector_select = ", COALESCE(p.sector, meta.sector) AS sector"
            elif "sector" in parquet_cols:
                sector_select = ", p.sector AS sector"
            elif metadata_join:
                sector_select = ", meta.sector AS sector"
            else:
                sector_select = ", NULL as sector"
            atr_select = (
                ", p.atr_14 AS atr_14"
                if "atr_14" in parquet_cols
                else ", NULL as atr_14"
            )

            # Daily prices view
            conn.execute(f"""
                CREATE OR REPLACE VIEW daily_prices AS
                SELECT
                    p.ticker as symbol,
                    p.Date as date,
                    p.Open as open,
                    p.High as high,
                    p.Low as low,
                    p.Close as close,
                    p.Volume as volume,
                    p."Adj Close" as adj_close
                    {atr_select}
                    {mkt_cap_select}
                    {sector_select},
                    p.SMA_10, p.SMA_20, p.EMA_10, p.EMA_20,
                    p.RSI_14, p.MACD
                FROM read_parquet('{parquet_path}') p
                {metadata_join}
            """)
            # Hourly prices view (if exists)
            if hourly_path.exists():
                conn.execute(f"""
                    CREATE OR REPLACE VIEW hourly_prices AS
                    SELECT * FROM read_parquet('{hourly_path}')
                """)

            # Verify
            result = conn.execute(
                "SELECT COUNT(*), MAX(date) FROM daily_prices"
            ).fetchone()
            conn.close()

            logger.info(f"DuckDB synced: {result[0]:,} rows, latest: {result[1]}")
            return True

        except Exception as e:
            logger.error(f"DuckDB sync failed: {e}")
            return False

    def sync_all(self) -> Dict[str, bool]:
        """
        Synchronize all data sources.

        Returns:
            Dict mapping source name to sync success
        """
        results = {}

        # Check status first
        status = self.check_sync_status()

        if status.get("all_synced"):
            logger.info("All data sources already synced")
            return {source: True for source in DATA_SOURCES.keys()}

        # Sync DuckDB if needed
        duckdb_status = status["sources"].get("market_data_duckdb", {})
        if not duckdb_status.get("is_current"):
            results["market_data_duckdb"] = self.sync_duckdb()
        else:
            results["market_data_duckdb"] = True

        # Other sources are read-only (generated by DownDay)
        for source in DATA_SOURCES.keys():
            if source != "market_data_duckdb":
                results[source] = status["sources"].get(source, {}).get("exists", False)

        return results

    def ensure_synced(self) -> bool:
        """
        Ensure all data is synced. Returns True if ready to use.

        Call this before any overnight research run.
        """
        # Note: avoid direct circular calls if ensure_core_market_data_ready imports this manager
        from autotrade.data_ingestion.bootstrap import ensure_core_market_data_ready
        ensure_core_market_data_ready(fail_fast=False)
        
        status = self.check_sync_status()

        if not status.get("primary_date"):
            logger.error("Primary data source unavailable - cannot proceed")
            return False

        if not status.get("all_synced"):
            logger.info("Data out of sync - syncing now...")
            results = self.sync_all()
            return all(results.values())

        return True

    def get_data_freshness(
        self,
        force_refresh: bool = False,
        reference_dt: Optional[datetime] = None,
    ) -> Dict[str, Any]:
        """
        Get data freshness summary for display.

        Returns:
            Human-readable freshness information
        """
        status = self.check_sync_status(force_refresh=force_refresh)

        checked_dt = _normalize_reference_datetime(reference_dt)
        primary_date = status.get("primary_date")
        expected_date = expected_core_market_data_date(reference_dt=checked_dt)

        if not primary_date:
            return {
                "status": "ERROR",
                "message": "Primary data unavailable",
                "primary_date": None,
                "expected_date": expected_date,
                "is_current": False,
            }

        is_current = str(primary_date)[:10] == expected_date
        days_old = (checked_dt - datetime.strptime(primary_date, "%Y-%m-%d")).days

        return {
            "status": "OK" if is_current else "STALE",
            "message": f"Data as of {primary_date}"
            + (
                " (current for this market session)"
                if is_current
                else f" ({days_old} days old, expected {expected_date})"
            ),
            "primary_date": primary_date,
            "expected_date": expected_date,
            "is_current": is_current,
            "ticker_count": status.get("primary_tickers", 0),
            "all_synced": status.get("all_synced", False),
        }


def _normalize_reference_datetime(reference_dt: Optional[datetime] = None) -> datetime:
    return reference_dt if isinstance(reference_dt, datetime) else get_market_now()


def _previous_business_day(day_value: date) -> date:
    """Returns the most recent trading day before the given date."""
    return last_trading_day(day_value - timedelta(days=1))


def evaluate_core_market_data_freshness(
    reference_dt: Optional[datetime] = None,
    require_all_synced: bool = True,
    force_refresh: bool = False,
) -> Dict[str, Any]:
    """Authoritative fail-closed readiness verdict for core market data."""
    manager = get_manager()
    try:
        status = manager.check_sync_status(force_refresh=force_refresh)
    except TypeError:
        status = manager.check_sync_status()
    primary_date = status.get("primary_date")
    expected_date = expected_core_market_data_date(reference_dt=reference_dt)
    checked_at = _normalize_reference_datetime(reference_dt).isoformat()
    blocking_reasons: list[str] = []
    age_days: Optional[int] = None

    if not primary_date:
        blocking_reasons.append("primary_data_unavailable")
    else:
        try:
            # Use pandas for robust parsing, normalize to naive for subtraction
            primary_dt = pd.to_datetime(primary_date).normalize().replace(tzinfo=None)
            ref_dt = pd.Timestamp(_normalize_reference_datetime(reference_dt).date()).replace(tzinfo=None)
            age_days = (ref_dt - primary_dt).days
        except Exception:
            age_days = None
            
        if str(primary_date)[:10] != expected_date:
            blocking_reasons.append(
                f"core_data_stale:{primary_date}->{expected_date}"
            )

    if require_all_synced and not bool(status.get("all_synced", False)):
        blocking_reasons.append("core_data_sources_out_of_sync")

    result = CoreDataFreshnessResult(
        is_fresh=not blocking_reasons,
        primary_date=primary_date,
        expected_date=expected_date,
        primary_tickers=int(status.get("primary_tickers", 0) or 0),
        all_synced=bool(status.get("all_synced", False)),
        age_days=age_days,
        checked_at=checked_at,
        blocking_reasons=blocking_reasons,
    )
    return result.to_dict()


# ============================================================================
# Module-level convenience functions
# ============================================================================

_manager: Optional[DataSyncManager] = None


def get_manager() -> DataSyncManager:
    """Get or create singleton DataSyncManager instance."""
    global _manager
    if _manager is None:
        _manager = DataSyncManager()
    return _manager


def check_sync() -> Dict[str, Any]:
    """Check sync status for all data sources."""
    return get_manager().check_sync_status()


def ensure_synced() -> bool:
    """Ensure all data is synced before use."""
    return get_manager().ensure_synced()


def get_freshness(
    force_refresh: bool = False,
    reference_dt: Optional[datetime] = None,
) -> Dict[str, Any]:
    """Get data freshness summary."""
    return get_manager().get_data_freshness(
        force_refresh=force_refresh,
        reference_dt=reference_dt,
    )


def get_core_market_data_readiness(
    reference_dt: Optional[datetime] = None,
    force_refresh: bool = False,
) -> Dict[str, Any]:
    """Return fail-closed readiness metadata for PM and market-hours workflows."""
    return evaluate_core_market_data_freshness(
        reference_dt=reference_dt,
        force_refresh=force_refresh,
    )


# ============================================================================
# CLI Interface
# ============================================================================

if __name__ == "__main__":
    import sys

    logging.basicConfig(
        level=logging.INFO, format="%(asctime)s | %(levelname)s | %(message)s"
    )

    manager = DataSyncManager()

    if len(sys.argv) > 1:
        command = sys.argv[1].lower()

        if command == "check":
            status = manager.check_sync_status()
            print(f"\n{'=' * 50}")
            print("Data Sync Status")
            print(f"{'=' * 50}")
            print(f"Primary Date: {status.get('primary_date')}")
            print(f"Tickers: {status.get('primary_tickers')}")
            print(f"All Synced: {status.get('all_synced')}")
            print("\nSources:")
            for name, info in status.get("sources", {}).items():
                sync_icon = "[OK]" if info.get("is_current") else "[!!]"
                print(f"  {sync_icon} {name}: {info.get('latest_date', 'N/A')}")

        elif command == "sync":
            results = manager.sync_all()
            print("\nSync Results:")
            for source, success in results.items():
                icon = "[OK]" if success else "[FAIL]"
                print(f"  {icon} {source}")

        elif command == "rebuild":
            print("Rebuilding DuckDB views...")
            success = manager.sync_duckdb(force=True)
            print(f"Rebuild: {'OK' if success else 'FAILED'}")

        else:
            print(f"Unknown command: {command}")
            print("Usage: python data_sync.py [check|sync|rebuild]")
    else:
        # Default: check and sync if needed
        freshness = manager.get_data_freshness()
        print(f"\nData Freshness: {freshness['status']}")
        print(f"  {freshness['message']}")

        if not freshness.get("all_synced"):
            print("\nSyncing...")
            manager.sync_all()
