"""
Market Intelligence Loader — Shared YouTube RAG Access

Provides a consistent interface for loading daily market intelligence reports
generated by the YouTube Daily Scanner. Used by:
  - project_chat.py (/report command and natural language)
  - premarket_manager.py (regime-aware gap filtering)
  - day_manager.py (intraday conviction adjustment)
  - autonomous_agent.py (overnight research engine)

Usage:
    from autotrade.utils.market_intelligence import load_market_intelligence
    intel = load_market_intelligence()  # tries today, falls back yesterday
    if intel:
        regime = intel.get("market_regime", "NEUTRAL")
        sizing = intel.get("trading_signals", {}).get("sizing_multiplier", 1.0)
"""

import json
import logging
import re
from pathlib import Path
from datetime import datetime, timedelta
from typing import Optional, Dict, Any, List

logger = logging.getLogger(__name__)

PROJECT_ROOT = Path(__file__).parent.parent.parent
DEFAULT_RAG_DIR = PROJECT_ROOT / "data" / "youtube" / "rag"


def load_market_intelligence(
    date_str: Optional[str] = None,
    rag_dir: Optional[Path] = None,
    fallback_days: int = 2,
) -> Optional[Dict[str, Any]]:
    """
    Load the most recent daily market intelligence report.
    
    Tries today first, then falls back up to `fallback_days` previous days.
    
    Args:
        date_str: Specific date to load (YYYY-MM-DD). If None, uses today.
        rag_dir: Path to RAG directory. Defaults to data/youtube/rag.
        fallback_days: How many prior days to check if target date has no report.
        
    Returns:
        Report dict with all fields from the consolidated report, or None.
    """
    rag = rag_dir or DEFAULT_RAG_DIR
    report_dir = rag / "daily_reports"
    
    if not report_dir.exists():
        logger.debug("No daily_reports directory found")
        return None
    
    # Build date candidates
    target = datetime.strptime(date_str.strip(), "%Y-%m-%d") if date_str else datetime.now()
    candidates = [target - timedelta(days=i) for i in range(fallback_days + 1)]
    
    for dt in candidates:
        ds = dt.strftime("%Y-%m-%d")

        # On Mondays, prefer the weekend consolidated report if available
        if dt.weekday() == 0:  # Monday
            weekend_file = report_dir / f"{ds}_weekend_consolidated.json"
            if weekend_file.exists():
                try:
                    with open(weekend_file, "r", encoding="utf-8") as f:
                        report = json.load(f)
                    report.setdefault("_meta", {})["_source"] = "weekend_consolidated"
                    if ds != target.strftime("%Y-%m-%d"):
                        report["_fallback_from"] = ds
                    logger.info(f"Loaded weekend intelligence report for {ds}")
                    return report
                except (json.JSONDecodeError, IOError) as e:
                    logger.warning(f"Failed to read weekend report {weekend_file}: {e}")

        report_file = report_dir / f"{ds}_consolidated.json"
        if report_file.exists():
            try:
                with open(report_file, "r", encoding="utf-8") as f:
                    report = json.load(f)
                if ds != target.strftime("%Y-%m-%d"):
                    logger.info(f"Using fallback report from {ds} (today's not available)")
                    report["_fallback_from"] = ds
                else:
                    logger.info(f"Loaded market intelligence for {ds}")
                # If report is markdown-only (raw_report without structured keys),
                # parse key trading fields from the markdown content.
                if "raw_report" in report and "market_regime" not in report:
                    _enrich_from_raw_report(report)
                return report
            except (json.JSONDecodeError, IOError) as e:
                logger.warning(f"Failed to read {report_file}: {e}")
    
    logger.info("No market intelligence report available")
    return None


def load_channel_extractions(
    date_str: Optional[str] = None,
    rag_dir: Optional[Path] = None,
) -> Dict[str, Dict]:
    """
    Load individual channel extractions for a specific date.
    
    Returns dict keyed by channel_key with extraction data.
    """
    rag = rag_dir or DEFAULT_RAG_DIR
    target = date_str or datetime.now().strftime("%Y-%m-%d")
    date_dir = rag / "by_date" / target
    
    extractions = {}
    if not date_dir.exists():
        return extractions
    
    for f in date_dir.glob("*.json"):
        channel_key = f.stem.rsplit("_", 1)[0]
        try:
            with open(f, "r", encoding="utf-8") as fh:
                extractions[channel_key] = json.load(fh)
        except (json.JSONDecodeError, IOError):
            pass
    
    return extractions


def _enrich_from_raw_report(report: Dict) -> None:
    """
    Convert a markdown-format raw_report into structured JSON fields.
    
    Primary: Uses local Ollama (fast 7B model) to accurately convert the
    full markdown content into the expected JSON schema — preserves all info.
    Fallback: Regex extraction if Ollama is unavailable.
    Mutates `report` in-place.
    """
    raw = report.get("raw_report", "")
    if not raw:
        return

    logger.info("Converting markdown raw_report to structured JSON via local Ollama")

    # Try Ollama conversion first (accurate, preserves all info)
    structured = _convert_markdown_to_json_ollama(raw)
    if structured:
        # Merge structured fields into report, keeping raw_report and _meta
        for key, value in structured.items():
            if key not in ("_meta", "raw_report"):
                report[key] = value
        report["_parsed_from_markdown"] = True
        report["_parse_method"] = "ollama"
        fields = [k for k in ("market_regime", "trading_signals", "smallcap_health",
                               "executive_summary", "overnight_directives") if k in report]
        logger.info(f"Ollama extracted {len(fields)} structured fields: {fields}")
        return

    # Fallback: regex extraction
    logger.warning("Ollama conversion failed, falling back to regex extraction")
    _enrich_from_raw_report_regex(report)


def _convert_markdown_to_json_ollama(markdown: str) -> Optional[Dict]:
    """
    Use local Ollama to convert markdown market intelligence report to structured JSON.
    
    Uses a fast model (qwen2.5-coder:7b) — the markdown is ~5K chars, this takes ~5-10s.
    Returns parsed dict or None on failure.
    """
    import requests as _requests

    # The exact JSON schema the system expects
    schema_example = '''{
    "date": "YYYY-MM-DD",
    "executive_summary": "2-3 sentence synthesis",
    "market_regime": "STRONG-RISK-ON | RISK-ON | LEAN-BULLISH | NEUTRAL | LEAN-BEARISH | RISK-OFF | CRASH",
    "regime_confidence": 70,
    "regime_summary": "1-2 sentence regime description",
    "smallcap_health": {
        "status": "healthy | cautious | defensive | danger",
        "iwm_assessment": "...",
        "breadth_assessment": "...",
        "rotation_signal": "..."
    },
    "trading_signals": {
        "sizing_multiplier": 0.6,
        "sizing_rationale": "why this multiplier",
        "sector_bias": [
            {"sector": "Small-Cap Financials", "bias": "overweight", "reason": "why"},
            {"sector": "Mega-Cap Tech", "bias": "avoid", "reason": "why"}
        ],
        "trigger_levels": {
            "spy": {"bull_above": 5419, "bear_below": 5402},
            "qqq": {"bull_above": 0, "bear_below": 593},
            "iwm": {"bull_above": 0, "bear_below": 0}
        },
        "time_alerts": ["economic event or data release"],
        "earnings_impact": ["tickers with earnings"]
    },
    "consensus": {
        "themes": ["theme1", "theme2"],
        "risks": ["risk1", "risk2"],
        "conflicts": [{"topic": "...", "bull_case": "...", "bear_case": "...", "resolution": "..."}]
    },
    "trade_ideas": [
        {"ticker": "XYZ", "mentioned_by": ["channel"], "direction": "long", "conviction": "high", "in_our_universe": true, "setup": "description"}
    ],
    "inverse_etf_signal": {
        "signal": "none | consider | strong",
        "instruments": ["SH", "PSQ"],
        "reason": "why"
    },
    "overnight_directives": [
        "Directive 1 for trading agent",
        "Directive 2"
    ],
    "channel_agreement": {
        "bullish_channels": [],
        "bearish_channels": [],
        "neutral_channels": [],
        "consensus_strength": "strong | moderate | mixed"
    }
}'''

    prompt = f"""Convert the following markdown market intelligence report into strict JSON.
Output ONLY valid JSON, no markdown formatting, no code fences, no explanation.
Preserve ALL information from the report — every sector, every level, every directive.
Use this exact JSON schema:

{schema_example}

RULES:
- market_regime MUST be one of: STRONG-RISK-ON, RISK-ON, LEAN-BULLISH, NEUTRAL, LEAN-BEARISH, RISK-OFF, CRASH
- If the report describes "rotation within risk-off" or "bifurcated", use LEAN-BEARISH
- sizing_multiplier must be a float between 0.0 and 1.5
- sector_bias entries: bias must be one of: overweight, neutral, underweight, avoid
- smallcap_health status must be one of: healthy, cautious, defensive, danger
- trigger_levels: use 0 if level not mentioned for an index
- Include ALL sectors mentioned in the report
- Include ALL directives/action items from the report

MARKDOWN REPORT:
{markdown}

JSON:"""

    # Try fast model first, then fallback
    models = ["qwen2.5-coder:7b", "qwen2.5:3b", "phi4:14b-q4_K_M"]
    ollama_url = "http://localhost:11434"

    for model in models:
        try:
            resp = _requests.post(
                f"{ollama_url}/api/chat",
                json={
                    "model": model,
                    "messages": [{"role": "user", "content": prompt}],
                    "stream": False,
                    "options": {
                        "temperature": 0.0,
                        "num_ctx": 8192,
                    },
                    "think": False,  # qwen3 compat — no internal reasoning
                },
                timeout=60,
            )
            resp.raise_for_status()
            content = resp.json().get("message", {}).get("content", "")

            if not content.strip():
                logger.warning(f"Ollama {model} returned empty content")
                continue

            # Strip any code fences the model might have added
            content = re.sub(r"^```(?:json)?\s*\n?", "", content.strip())
            content = re.sub(r"\n?```\s*$", "", content.strip())
            # Strip think tags if present
            content = re.sub(r"<think>.*?</think>", "", content, flags=re.DOTALL).strip()

            parsed = json.loads(content)
            if isinstance(parsed, dict) and any(k in parsed for k in ("market_regime", "trading_signals", "executive_summary")):
                logger.info(f"Ollama {model} successfully converted markdown to JSON ({len(parsed)} keys)")
                return parsed
            else:
                logger.warning(f"Ollama {model} returned JSON but missing expected keys")
                continue

        except _requests.ConnectionError:
            logger.warning("Ollama not available (connection refused)")
            return None  # No point trying other models if Ollama is down
        except _requests.Timeout:
            logger.warning(f"Ollama {model} timed out on markdown conversion")
            continue
        except json.JSONDecodeError as e:
            logger.warning(f"Ollama {model} returned non-JSON: {e}")
            # Try to extract JSON from the response
            json_match = re.search(r"\{.*\}", content, re.DOTALL)
            if json_match:
                try:
                    parsed = json.loads(json_match.group(0))
                    if isinstance(parsed, dict) and "market_regime" in parsed:
                        logger.info(f"Ollama {model} JSON extracted from mixed output")
                        return parsed
                except json.JSONDecodeError:
                    pass
            continue
        except Exception as e:
            logger.warning(f"Ollama {model} conversion failed: {e}")
            continue

    logger.warning("All Ollama models failed for markdown→JSON conversion")
    return None


def _enrich_from_raw_report_regex(report: Dict) -> None:
    """
    Regex fallback: extract structured fields from markdown when Ollama is unavailable.
    Less accurate but works offline. Mutates `report` in-place.
    """
    raw = report.get("raw_report", "")
    if not raw:
        return

    logger.info("Extracting structured fields from markdown via regex (fallback)")

    # ── Market Regime ─────────────────────────────────────────────
    regime_patterns = [
        r'["\u201c]\s*(SECTOR[\s-]*ROTATION\s*WITHIN\s*RISK[\s-]*OFF)\s*["\u201d]',
        r'["\u201c]\s*(BIFURCATED\s*ROTATION)\s*["\u201d]',
        r"(?:market\s*)?regime[:\s]*[\*\"'\u201c\u201d]*\s*(STRONG[\s-]?RISK[\s-]?ON|RISK[\s-]?ON|LEAN[\s-]?BULLISH|NEUTRAL|LEAN[\s-]?BEARISH|RISK[\s-]?OFF|CRASH)",
        r"regime[:\s]+[\*\"'\u201c\u201d]*\s*([A-Z][A-Z\s-]{3,25}?)[\*\"'\u201c\u201d]*\s*(?:\(|$|\n|\u2014|\u2013)",
    ]
    regime = "NEUTRAL"
    for pat in regime_patterns:
        m = re.search(pat, raw, re.IGNORECASE)
        if m:
            regime = m.group(1).strip().strip("*\"\u201c\u201d' ").upper()
            if "ROTATION" in regime and "RISK-OFF" in regime:
                regime = "LEAN-BEARISH"
            elif "BIFURCATED" in regime or "SECTOR-ROTATION" in regime:
                regime = "LEAN-BEARISH"
            break
    report["market_regime"] = regime

    # ── Regime Confidence ─────────────────────────────────────────
    m = re.search(r"confidence[:\s]*[\*]*\s*(\d{1,3})\s*%?", raw, re.IGNORECASE)
    report["regime_confidence"] = int(m.group(1)) if m else 50

    # ── Sizing Multiplier ─────────────────────────────────────────
    m = re.search(r"sizing\s*multiplier[:\s]*[\*]*\s*[\*]*([\d.]+)", raw, re.IGNORECASE)
    if m:
        try:
            sizing = float(m.group(1))
            if 0.0 <= sizing <= 2.0:
                report.setdefault("trading_signals", {})["sizing_multiplier"] = sizing
        except ValueError:
            pass

    # ── Sector Bias (from markdown tables) ────────────────────────
    sector_biases = []
    table_rows = re.findall(
        r"\|\s*\*{0,2}([^|*]+?)\*{0,2}\s*\|\s*\*{0,2}([^|*]+?)\*{0,2}\s*\|\s*\*{0,2}(OVERWEIGHT|UNDERWEIGHT|NEUTRAL|AVOID)[^|]*\|",
        raw, re.IGNORECASE,
    )
    for sector_name, status, bias in table_rows:
        sector_name = sector_name.strip().strip("*")
        bias = bias.strip().upper()
        if sector_name.lower() in ("sector", "metric", "parameter", "---"):
            continue
        sector_biases.append({"sector": sector_name, "bias": bias.lower(), "reason": status.strip()})
    if sector_biases:
        report.setdefault("trading_signals", {})["sector_bias"] = sector_biases

    # ── Small-Cap Health ──────────────────────────────────────────
    m = re.search(
        r"small[\s-]*cap\s+health.*?status[:\s]*\*{0,2}\s*(HEALTHY|IMPROVING|CAUTIOUS|DEFENSIVE|DANGER|CRITICAL)",
        raw, re.IGNORECASE | re.DOTALL,
    )
    if m:
        status_map = {"IMPROVING": "cautious", "CRITICAL": "danger"}
        raw_status = m.group(1).upper()
        report["smallcap_health"] = {"status": status_map.get(raw_status, raw_status.lower())}

    # ── Executive Summary ─────────────────────────────────────────
    m = re.search(
        r"(?:executive\s*summary|key\s*shift)[^\n]*\n+[-*\s]*(.*?)(?=\n---|\n###|\n\n\n)",
        raw, re.IGNORECASE | re.DOTALL,
    )
    if m:
        summary = re.sub(r"\*{1,2}", "", m.group(1)).strip()
        sentences = re.split(r"(?<=[.!])\s+", summary)
        report["executive_summary"] = " ".join(sentences[:3])

    # ── Overnight/Agent Directives ────────────────────────────────
    directives = []
    m = re.search(
        r"(?:agent\s*action|directive|instruction)[^\n]*\n(.*?)(?=\n---|\n###|\Z)",
        raw, re.IGNORECASE | re.DOTALL,
    )
    if m:
        for line in m.group(1).split("\n"):
            line = line.strip().lstrip("0123456789.)-* ")
            line = re.sub(r"\*{1,2}", "", line).strip()
            if len(line) > 15 and not line.startswith("|") and not line.startswith("---"):
                directives.append(line)
    if directives:
        report["overnight_directives"] = directives[:10]

    raw_upper = raw.upper()
    if any(
        marker in raw_upper
        for marker in ("MAXIMUM DEFENSIVE", "NO NEW LONGS", "RISK-OFF CONFIRMED")
    ):
        report["market_regime"] = "RISK-OFF"
        report["regime_confidence"] = max(
            int(report.get("regime_confidence", 50) or 50),
            80,
        )
        trading_signals = report.setdefault("trading_signals", {})
        current_sizing = trading_signals.get("sizing_multiplier", 1.0)
        try:
            current_sizing = float(current_sizing)
        except (TypeError, ValueError):
            current_sizing = 1.0
        trading_signals["sizing_multiplier"] = min(current_sizing, 0.25)
        smallcap_health = report.setdefault("smallcap_health", {})
        smallcap_health["status"] = "danger"
        if "overnight_directives" not in report:
            report["overnight_directives"] = [
                "NO NEW LONGS until market breadth and index support stabilize.",
                "Remain maximum defensive and prioritize capital preservation.",
            ]

    report["_parsed_from_markdown"] = True
    report["_parse_method"] = "regex_fallback"
    fields = [k for k in ("market_regime", "trading_signals", "smallcap_health",
                            "executive_summary", "overnight_directives") if k in report]
    logger.info(f"Regex extracted {len(fields)} structured fields: {fields}")


def get_regime(report: Optional[Dict] = None) -> str:
    """Extract market regime from a report. Returns 'NEUTRAL' if unavailable."""
    if not report:
        report = load_market_intelligence()
    if not report:
        return "NEUTRAL"
    return report.get("market_regime", "NEUTRAL")


def get_sizing_multiplier(report: Optional[Dict] = None) -> float:
    """Extract position sizing multiplier. Returns 1.0 if unavailable."""
    if not report:
        report = load_market_intelligence()
    if not report:
        return 1.0
    signals = report.get("trading_signals", {})
    return float(signals.get("sizing_multiplier", 1.0))


def get_sector_bias(report: Optional[Dict] = None) -> List[Dict]:
    """Extract sector bias list. Returns empty list if unavailable."""
    if not report:
        report = load_market_intelligence()
    if not report:
        return []
    signals = report.get("trading_signals", {})
    return signals.get("sector_bias", [])


def get_overnight_directives(report: Optional[Dict] = None) -> List[str]:
    """Extract overnight directives. Returns empty list if unavailable."""
    if not report:
        report = load_market_intelligence()
    if not report:
        return []
    return report.get("overnight_directives", report.get("agent_actions", []))


def format_report_for_display(report: Dict) -> str:
    """
    Format a market intelligence report for human-readable display in chat.
    
    This produces the rich text output shown when a user types /report
    or asks "give me a market report".
    """
    if not report:
        return "No market intelligence available."
    
    meta = report.get("_meta", {})
    date = meta.get("date", report.get("date", "Unknown"))
    channels = meta.get("channels_included", [])
    model = meta.get("model", "unknown")
    
    lines = []
    lines.append(f"{'='*65}")
    lines.append(f"  DAILY MARKET INTELLIGENCE REPORT — {date}")
    lines.append(f"  Sources: {', '.join(channels)} | Model: {model}")
    lines.append(f"{'='*65}")
    
    # Fallback notice
    if report.get("_fallback_from"):
        lines.append(f"\n  ⚠  Using previous day's report ({report['_fallback_from']})")
    
    # === Executive Summary ===
    summary = report.get("executive_summary", report.get("regime_summary", ""))
    if summary:
        lines.append(f"\n## Executive Summary\n{summary}")
    
    # === Regime ===
    regime = report.get("market_regime", "UNKNOWN")
    confidence = report.get("regime_confidence", "?")
    lines.append(f"\n## Market Regime: {regime} (confidence: {confidence}%)")
    regime_desc = report.get("regime_summary", "")
    if regime_desc and regime_desc != summary:
        lines.append(f"  {regime_desc}")
    
    # === Small-Cap Health ===
    sc = report.get("smallcap_health", {})
    if sc:
        lines.append(f"\n## Small-Cap Health: {sc.get('status', 'unknown').upper()}")
        if sc.get("iwm_assessment"):
            lines.append(f"  IWM: {sc['iwm_assessment']}")
        if sc.get("breadth_assessment"):
            lines.append(f"  Breadth: {sc['breadth_assessment']}")
        if sc.get("rotation_signal"):
            lines.append(f"  Rotation: {sc['rotation_signal']}")
    
    # === Trading Signals ===
    signals = report.get("trading_signals", {})
    if signals:
        sizing = signals.get("sizing_multiplier", "N/A")
        lines.append(f"\n## Trading Signals")
        lines.append(f"  Position Sizing: {sizing}x")
        if signals.get("sizing_rationale"):
            lines.append(f"  Rationale: {signals['sizing_rationale']}")
        
        sectors = signals.get("sector_bias", [])
        if sectors:
            lines.append(f"\n  Sector Bias:")
            for s in sectors:
                lines.append(f"    {s.get('sector', '?')}: {s.get('bias', '?')} — {s.get('reason', '')}")
        
        triggers = signals.get("trigger_levels", {})
        if triggers:
            lines.append(f"\n  Key Levels:")
            for idx, lvls in triggers.items():
                bull = lvls.get("bull_above", "?")
                bear = lvls.get("bear_below", "?")
                lines.append(f"    {idx.upper()}: bull above {bull} / bear below {bear}")
        
        time_alerts = signals.get("time_alerts", [])
        if time_alerts:
            lines.append(f"\n  Time Alerts:")
            for ta in time_alerts:
                lines.append(f"    ⏰ {ta}")
    
    # === Position Sizing (legacy format) ===
    ps = report.get("position_sizing", {})
    if ps and not signals:
        lines.append(f"\n## Position Sizing: {ps.get('recommendation', 'N/A')}")
        lines.append(f"  Reason: {ps.get('reason', '')}")
    
    # === Consensus ===
    consensus = report.get("consensus", {})
    themes = consensus.get("themes", report.get("consensus_themes", []))
    risks = consensus.get("risks", report.get("consensus_risks", []))
    
    if themes:
        lines.append(f"\n## Consensus Themes")
        for t in themes:
            lines.append(f"  • {t}")
    
    if risks:
        lines.append(f"\n## Key Risks")
        for r in risks:
            lines.append(f"  ⚠ {r}")
    
    conflicts = consensus.get("conflicts", [])
    if conflicts:
        lines.append(f"\n## Channel Conflicts")
        for c in conflicts:
            lines.append(f"  {c.get('topic', '?')}: Bull={c.get('bull_case', '')} vs Bear={c.get('bear_case', '')}")
            if c.get("resolution"):
                lines.append(f"    → Resolution: {c['resolution']}")
    
    # === Trade Ideas ===
    ideas = report.get("trade_ideas", report.get("trade_ideas_overlap", []))
    if ideas:
        lines.append(f"\n## Trade Ideas ({len(ideas)})")
        for idea in ideas:
            ticker = idea.get("ticker", "?")
            direction = idea.get("direction", "?")
            conviction = idea.get("conviction", "")
            mentioned = ", ".join(idea.get("mentioned_by", []))
            in_universe = "✅" if idea.get("in_our_universe") else "❌"
            lines.append(f"  {ticker} ({direction}) {in_universe} [{conviction}] — from: {mentioned}")
            if idea.get("setup"):
                lines.append(f"    Setup: {idea['setup']}")
    
    # === Inverse ETF ===
    inv = report.get("inverse_etf_signal", {})
    if inv and inv.get("signal", "none") != "none":
        lines.append(f"\n## Inverse ETF Signal: {inv.get('signal', 'none').upper()}")
        lines.append(f"  Instruments: {', '.join(inv.get('instruments', []))}")
        lines.append(f"  Reason: {inv.get('reason', '')}")
    
    # === Channel Agreement ===
    agree = report.get("channel_agreement", {})
    if agree:
        lines.append(f"\n## Channel Agreement: {agree.get('consensus_strength', 'unknown').upper()}")
        if agree.get("bullish_channels"):
            lines.append(f"  Bullish: {', '.join(agree['bullish_channels'])}")
        if agree.get("bearish_channels"):
            lines.append(f"  Bearish: {', '.join(agree['bearish_channels'])}")
        if agree.get("neutral_channels"):
            lines.append(f"  Neutral: {', '.join(agree['neutral_channels'])}")
    
    # === Overnight Directives ===
    directives = report.get("overnight_directives", report.get("agent_actions", []))
    if directives:
        lines.append(f"\n## Agent Directives")
        for i, d in enumerate(directives, 1):
            lines.append(f"  {i}. {d}")
    
    lines.append(f"\n{'='*65}")
    
    return "\n".join(lines)


def format_report_for_llm_context(report: Dict) -> str:
    """
    Format a report as compact context to inject into LLM prompts.
    
    Used when the agent needs market context for decision-making,
    but doesn't need the full pretty-printed version.
    """
    if not report:
        return ""
    
    compact = {
        "regime": report.get("market_regime", "NEUTRAL"),
        "confidence": report.get("regime_confidence", 50),
        "summary": report.get("executive_summary", report.get("regime_summary", "")),
        "smallcap_status": report.get("smallcap_health", {}).get("status", "unknown"),
    }
    
    signals = report.get("trading_signals", {})
    if signals:
        compact["sizing_multiplier"] = signals.get("sizing_multiplier", 1.0)
        compact["sector_bias"] = signals.get("sector_bias", [])
    else:
        ps = report.get("position_sizing", {})
        compact["sizing"] = ps.get("recommendation", "full")
    
    compact["directives"] = report.get("overnight_directives", report.get("agent_actions", []))
    compact["risks"] = report.get("consensus", {}).get("risks", report.get("consensus_risks", []))
    
    return json.dumps(compact, indent=2)
